github:
  token: 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
spring:
  application:
    name: dynamicproperty
  profiles:
    active: prod1
server:
  port: '8080'
custom:
  mongodb:
    url: mongodb+srv://priyanshu:soumik@sprinklr.emlaafp.mongodb.net/?retryWrites=true&w=majority
    database: prod1



