spring:
  application:
    name: dynamicproperty
  data:
    mongodb:
      database: prod1
      port: '27017'
      host: localhost
  profiles:
    active: prod1
server:
  port: '8080'
custom:
  mongodb:
    url: mongodb://localhost:27017/prod1


