github:
  token: 
  api:
    url: https://raw.githubusercontent.com/PriyanshuGagiya/DP/
spring:
  application:
    name: dynamicproperty
  profiles:
    active: prod1
server:
  port: '8080'
custom:
  mongodb:
    # url: mongodb+srv://priyanshu:soumik@sprinklr.emlaafp.mongodb.net/?retryWrites=true&w=majority
    url: mongodb://localhost:27017
    database: prod1



